application: mf-2-0
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:  
- url: /static
  static_dir: static

- url: /payment/?[0-9]*
  script: httpHandlers/payment.py

- url: /tag/?[0-9]*
  script: httpHandlers/tag.py
  
- url: /t2p/?[0-9]*
  script: httpHandlers/T2p.py

- url: /.*
  script: httpHandlers/index.py
