application: mf-2-0
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:  
- url: /static
  static_dir: static

- url: /api/all
  script: httpHandlers/all.py

- url: /api/payment/?[0-9]*
  script: httpHandlers/payment.py

- url: /api/tag/?[0-9]*
  script: httpHandlers/tag.py
  
- url: /api/t2p/?[0-9]*
  script: httpHandlers/t2p.py
  
- url: /api/vault/?[0-9]*
  script: httpHandlers/vault.py
  
- url: /api/filter/?[0-9]*
  script: httpHandlers/filter.py

- url: /.*
  script: httpHandlers/index.py
