application: mf-2-0
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:  
- url: /static
  static_dir: static

- url: /api/(all|payment|tag|vault|t2p|filter)/?([0-9]*)
  script: httpHandlers/REST.py

- url: /.*
  script: httpHandlers/index.py
